# compose-flaresolverr.yml
version: ${DOCKER_COMPOSE_VERSION:-3.8}

networks:
  ${PROXY_NETWORK:-proxy-public-net}:        # Network for reverse proxy traffic
    external: true

services:
  flaresolverr:
    env_file:
      - ../env-docker.env             # Global environment variables
      - ./env-flaresolverr.env        # Application-specific environment variables
    image: ${FLARESOLVERR_IMAGE:-ghcr.io/flaresolverr/flaresolverr:latest}
    container_name: ${CONTAINER_NAME:-flaresolverr}
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ:-Europe/Paris}        # Timezone configuration
    healthcheck:
      test: 
        - "CMD"
        - "/bin/sh"
        - "-c"
        - "wget --no-verbose --tries=1 --spider http://localhost:${APP_PORT:-8191}/health"
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-20s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-40s}
    networks:
      - ${PROXY_NETWORK:-proxy-public-net}
    labels:
      # Enable automatic updates through Watchtower
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped