version: ${DOCKER_COMPOSE_VERSION:-3.7}

# What is this?
#
# This stack exists solely to deploy the notification-net bridge network, so that
# other stacks can attach to it and use mailrise for ntoifications

networks:
  ${NOTIFICATION_NETWORK:-notification-net}:
    name: ${NOTIFICATION_NETWORK:-notification-net}
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: ${NOTIFICATION_NETWORK_SUBNET:-172.24.1.0/24}

services:
  ${NOTIFICATION_NETWORK:-notification-net}:
    env_file:
      - ../env-docker.env    # Global environment variables
    image: containous/whoami
    container_name: ${NOTIFICATION_NETWORK:-notification-net}
    networks:
      - ${NOTIFICATION_NETWORK:-notification-net}
    restart: unless-stopped