version: ${DOCKER_COMPOSE_VERSION:-3.7}

networks:
  ${PROXY_NETWORK:-proxy-public-net}:          # Network for reverse proxy traffic
    external: true
  ${NOTIFICATION_NETWORK:-notification-net}:   # Network for notification services
    external: true

services:
 bitwarden:
   env_file:
     - ../env-docker.env    # Global environment variables
     - ./env-bitwarden.env     # Application-specific environment variables
   image: ${BITWARDEN_IMAGE:-vaultwarden/server:latest}
   container_name: ${CONTAINER_NAME:-bitwarden}
   environment:
      DOMAIN: "https://${BITWARDEN_SUBDOMAIN:-vault}.${BASE_DOMAIN:-yourdomain.com}/"
   volumes:
     - ${DATA_PATH:-./data}:/data                     # Data configuration path
   networks:
     - ${PROXY_NETWORK:-proxy-public-net}           # For reverse proxy access
     - ${NOTIFICATION_NETWORK:-notification-net}    # For notifications
   healthcheck:
     test: 
       - "CMD"
       - "/bin/sh"
       - "-c"
       - "wget --no-verbose --tries=1 --spider http://localhost:${APP_PORT:-80}/ && wget --no-verbose --tries=1 --spider https://${BITWARDEN_SUBDOMAIN:-vault}.${BASE_DOMAIN:-yourdomain.com}/"
     interval: ${HEALTHCHECK_INTERVAL:-30s}
     timeout: ${HEALTHCHECK_TIMEOUT:-20s}
     retries: ${HEALTHCHECK_RETRIES:-3}
     start_period: ${HEALTHCHECK_START_PERIOD:-40s}
   labels:
     # Basic Traefik setup
     - traefik.enable=true
     - traefik.docker.network=${PROXY_NETWORK:-proxy-public-net}
     # HTTP configuration with automatic HTTPS redirect
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-http.rule=Host(`${BITWARDEN_SUBDOMAIN:-vault}.${BASE_DOMAIN:-yourdomain.com}`)
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-http.entrypoints=http
     - traefik.http.middlewares.httptohttps.redirectscheme.scheme=https
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-http.middlewares=httptohttps
     # HTTPS configuration with SSL
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.rule=Host(`${BITWARDEN_SUBDOMAIN:-vault}.${BASE_DOMAIN:-yourdomain.com}`)
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.entrypoints=https
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.tls.certresolver=${CERT_RESOLVER:-dnschallengeovh}
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.tls.domains[0].main=*.${BASE_DOMAIN:-yourdomain.com}
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.tls.domains[0].sans=${BASE_DOMAIN:-yourdomain.com}
     # Service definition
     - traefik.http.routers.${CONTAINER_NAME:-bitwarden}-https.service=${CONTAINER_NAME:-bitwarden}_server_service
     - traefik.http.services.${CONTAINER_NAME:-bitwarden}_server_service.loadbalancer.server.port=${APP_PORT:-80}
     # Enable automatic updates through Watchtower
     - com.centurylinklabs.watchtower.enable=true
   restart: unless-stopped
